### ISSUE TITLE
How is Deep Linking done?

### ISSUE THREAD

**Issue by emrepirnaz** [victorkvarghese/react-native-boilerplate#11]
It works in the structure I installed with `react-navigation` but it doesn't work in your boilerplate. Can you share a document on this subject? I can run as `myapp://` but I can't run as `myapp://routename`.

**Comment by victorkvarghese** [comment]
I didn't get what you're saying. You mean `react-navigation` is not working on this boilerplate ??

**Comment by emrepirnaz** [comment]
Deep Linking does not work on your react-navigation configuration. Try.

**Comment by victorkvarghese** [comment]
Did u do follow the guide properly. You need to make some change sin iOs and Android native side to enable deep linking. this boilerplate doesn't support deep linking by default.

Please follow the section `Set up with react-native init projects` [here(https://reactnavigation.org/docs/en/deep-linking.html)

**Comment by emrepirnaz** [comment]
I said that it doesn't work in the structure you created, but I think you insist on not understanding it. Thank you.
