### ISSUE TITLE
error Failed to install the app. 

### ISSUE THREAD

**Issue by Ladvace** [victorkvarghese/react-native-boilerplate#14]
when I try to run the app with `react-native run-android`  the output is:

```
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

```

**Comment by victorkvarghese** [comment]
@Ladvace 
Make sure your development environment is setup. Also for android, you can try using Android studio.

if command line make sure dependencies are installed and SDK location is defined on android/local.properties (This is taken care automatically while using android studio)
