### ISSUE TITLE
Add Example for call API and change state.

### ISSUE THREAD

**Issue by pqv2210** [victorkvarghese/react-native-boilerplate#18]
Hi, I'm new to redux-saga and I don't know how to change the state and call the API use Redux and Redux-saga.
Can you add some example in your project?
Thank you! 😄

**Comment by victorkvarghese** [comment]
@pqv2210 
You can see the commented code in loginSaga.

loginSaga gets invoked when you dispatch LOGIN_REQUEST. Saga contains how to call api (loginUser will be an async fetch)
* Use call for async operations like fetch and used put to dispatch changes in redux.
* when you click on login, the same process is happening, just the api code is commented out as it requires config in iOS.
