### ISSUE TITLE
Unable to resolve modules

### ISSUE THREAD

**Issue by dakkafex** [victorkvarghese/react-native-boilerplate#19]
trying to run the app from a fresh clone but i keep getting this error

``error: Error: Unable to resolve module `app/navigation` from `app\Entrypoint.tsx`: app/navigation could not be found within the project.``

**Comment by victorkvarghese** [comment]
@dakkafex couldn't reproduce this issue
can you try fresh install. Make sure all dependencies are installed.
Also make sure package.json is present inside app folder
