### ISSUE TITLE
Adding redux on navigation

### ISSUE THREAD

**Issue by hemel-cse** [victorkvarghese/react-native-boilerplate#2]
Hi,
I am using the boilerplate for one of my [project](https://github.com/hemel-cse/ipcapp). It's good.
you can add redux navigation.
In the saga the navigation action is throwing error. 
`yield put(navigationActions.navigateToHomeScreen({}));`
Can you show a working example?

**Comment by victorkvarghese** [comment]
@hemel-cse Redux navigation is soon going to be deprecated.
naviagtionActions has some changes based on the new react-navigation service used.

I will update the code using the new code and include an example for navigation as well.

Expect a new commit today ...

**Comment by victorkvarghese** [comment]
Closed  [232e119e1569cdc555da4e145c47a4e6658392a9](https://github.com/victorkvarghese/react-native-boilerplate/commit/232e119e1569cdc555da4e145c47a4e6658392a9)

**Comment by hemel-cse** [comment]
Thanks for the update. Appreciate it.

**Comment by hemel-cse** [comment]
Hi,
@victorkvarghese 
From the saga dispatching action without type properties throwing error.
`yield put(navigationActions.navigateToHomeScreen({}));`
