### ISSUE TITLE
Can't integrate with Firebase

### ISSUE THREAD

**Issue by sajumani** [victorkvarghese/react-native-boilerplate#27]
Hi,

I have an issue, when i trying to integrate firebase authentication.

Seems it has to update more Packages, While i upgrading one by one it not running

Have you upgrade to latest version ?

**Comment by victorkvarghese** [comment]
This boilerplate doesn't use firebase. Please provide more info on why it's not working. Reopen if needed

PS: you can update any packages in the boilerplate, and. it should work unless some code changes in the dependencies

**Comment by sajumani** [comment]
yarn add @react-native-firebase/auth

I added this package, But it always shows unable to resolve module 

Any reason why ?

**Comment by sajumani** [comment]
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99'

**Comment by victorkvarghese** [comment]
You need to update the deployment target in xcode.

**Comment by sajumani** [comment]
post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
  end
 end
end

Am trying this

**Comment by sajumani** [comment]
CompileC /Users/apple/Library/Developer/Xcode/DerivedData/krida-egtxqflyffbovmgrlmwiugqysmyj/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper-PeerTalk.build/Objects-normal/x86_64/PTUSBHub.o /Volumes/STORAGE/krida_v2/ios/Pods/Flipper-PeerTalk/peertalk/PTUSBHub.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Flipper-PeerTalk' from project 'Pods')

Again getting this error

**Comment by sajumani** [comment]
yarn add @react-native-google-signin/google-signin
yarn add react-native-fbsdk
yarn add @invertase/react-native-apple-authentication

Want to add these ... 
Getting more errors, Will be helpful, if you can give solution
