### ISSUE TITLE
Specify initial route.

### ISSUE THREAD

**Issue by hasanshahoud** [victorkvarghese/react-native-boilerplate#3]
#### After I ran the app, I wanted to check which screen is rendered first, that took me a minute to figure it out. Because in the `NavigationStack.js` I couldn't see which one is the initial route.
I understand now what you place as a first property to the config object that you pass to the `createStackNavigator`, becomes the first route that renders. However, passing another object with `initialRouteName` property makes it easier to read and understand.

> I am new to RN, let me know if that does/n't matter.

**Comment by hemel-cse** [comment]
Hi @hasanshahoud, I have built few screen with this boilerplate. You can look into [here](https://github.com/hemel-cse/ipcapp/blob/master/app/navigation/NavigationStack.js) to understand the navigation's.

**Comment by victorkvarghese** [comment]
When the number of screens are too far high, its better to use initialRouteName which might help debugging 

Closed  [#ed12b30](https://github.com/victorkvarghese/react-native-boilerplate/commit/ed12b30ac4ba0fe5d85c6a9460f0ebd13f006426)
