### ISSUE TITLE
Attempt to invoke interface method 'boolean.com.swmansion.reanimated.layoutReanimation.NativeMethodsHolder.isLayoutAnimationEnabled()' on null object reference

### ISSUE THREAD

**Issue by dguard** [victorkvarghese/react-native-boilerplate#35]
### Help us reproduce - tell us about your environment
1. Ubuntu
2. Android
3. Latest Master

### Steps to reproduce
1. git clone https://github.com/victorkvarghese/react-native-boilerplate
2. npx react-native-rename reactnativeboilerplate
3. yarn install
4. yarn start
5. npx react-native run-android

### Expected result
1. It should run successfully on android

### Actual result

![Screenshot_20220108-143418_dcreactnativeboilerplate](https://user-images.githubusercontent.com/1911516/148639424-749f4906-a25d-4527-82ec-a12c6ed7f9c5.jpg)

**Comment by dguard** [comment]
Fixed with this:
https://github.com/software-mansion/react-native-reanimated/issues/2702#issuecomment-1001948192

Just use different version react-native-reanimated
```"react-native-reanimated": "2.2.4"```

**Comment by victorkvarghese** [comment]
Fixed with [commit](https://github.com/victorkvarghese/react-native-boilerplate/commit/f3645ad2e372da949a32bbb4374a7c9497392907)
