### ISSUE TITLE
Redux saga action is not defined.

### ISSUE THREAD

**Issue by webmasterdragon** [victorkvarghese/react-native-boilerplate#8]
Hi @victorkvarghese 
Thanks for supporting this boilerplate.
I like this one and determined to start with this boilerplate for my project.
I have issue using redux-saga for api integration.
Just now enabled your [commented](https://github.com/victorkvarghese/react-native-boilerplate/blob/807905444825c96d54e371dfce4eb4e6d5bee151/app/sagas/loginSaga.js#L20) login saga and test but have above issue.
Looking forward to your feedback asap.

**Comment by victorkvarghese** [comment]
whats the issue?

FYI: 
`    //const response = yield call(loginUser, action.username, action.password);
`
This commented part is an api call. loginUser is an exported function that accepts username and password. uses fetch to call the api and returns the response.

**Comment by webmasterdragon** [comment]
After uncomment above line, i got `action is not defined` issue.

**Comment by victorkvarghese** [comment]
oh yeah that .. u need add action as a parameter to the saga function

`export default function* loginAsync(action) {`

**Comment by webmasterdragon** [comment]
OK. Thanks.

**Comment by victorkvarghese** [comment]
@webmasterdragon FYI: project upgraded to latest version 0.59.4

**Comment by webmasterdragon** [comment]
Thanks I have already upgrade myself when I start. 🤒
