### ISSUE TITLE
How can I run it with Expo?

### ISSUE THREAD

**Issue by HeroSony** [victorkvarghese/react-native-boilerplate#9]

**Comment by vnlebaoduy** [comment]
You can copy structure this project and add lib in package.json

**Comment by Victor-Varghese** [comment]
It's not an expo project. But u can 

1. setup an expo project on your own.
2. install dependencies 
3. use the src folder to follow the boilerplate guidelines

**Comment by victorkvarghese** [comment]
It's not an expo project. But u can

1. setup an expo project on your own.
2. install dependencies
3. use the src folder to follow the boilerplate guidelines
